### ISSUE TITLE
Using Webauthn for login

### ISSUE THREAD

**Issue by joaosantos15** [ipfs-shipyard/js-idm-wallet#5]
Hey, all,

Following up on the conversations and work being done to use webauthn login, I followed @satazor advice and split the webauth service worker project into separate libraries. 
We now have:
* [client-lib](https://github.com/joaosantos15/webauthn-ws-client)
* [service-worker-lib](https://github.com/joaosantos15/webauthn-sw)

There is also a [repo with a usage example, here](https://github.com/joaosantos15/webauthn-sw-example).

Let me know what are the next steps in order for this to be used in the IDM 😁

**Comment by satazor** [comment]
@joaosantos15 sorry for the late response. I created a new issue on our management repo: https://github.com/ipfs-shipyard/pm-idm/issues/147.

Lets track progress there.
